# Server configuration
server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

# Logging configuration
logging:
  file:
    name: logs/rentacar.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    com.rentacar: DEBUG

# Database Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rentacarDB
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Security Configuration
rentacar:
  app:
    jwt:
      # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      secret-key: 1I3G3IUWEPs3qoy+4Ps8SVKeL6yB6ukc8+/T6oo9FpB9jgmgzBaGj3AnvLrEFD/btnY5XZ7Egcg8RCYkQUItfNfQ4v091qIbfQ93nk5JC8g46YoDDrqKJH4L50MNFwbvHQHuLCyc0Uz665KlCD3n6r6YnJHTUAGcQcSeiZh15ZM=
      expiration-ms: 86400000

# Swagger-ui custom path
springdoc:
  swagger-ui:
    path: /rentacar-ui